Update setup

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -530,20 +530,30 @@ check_resource() {
         printf "\r\033[1E\033[K" | tee -a "${LOG_FILE}"
     fi
 
-    # Check free space of /var 
-    info "'/var' free space (MiB):      $(df -m /var | awk 'NR==2 {print $4}')"
-    if [ $(df -m /var | awk 'NR==2 {print $4}') -lt ${REQUIRED_VAR_FREE} ]; then
-        printf "\r\033[3F\033[K$(date) [INFO]: Checking required resource.....................ng\n" | tee -a "${LOG_FILE}"
-        printf "\r\033[3E\033[K" | tee -a "${LOG_FILE}"
-        error "Lack of free space! Required at least ${REQUIRED_VAR_FREE} Bytes free space on /var directory."
-    fi
+    if [ "${DEP_PATTERN}" != "RHEL8" ]; then
+        # Check free space of /var
+        info "'/var' free space (MiB):      $(df -m /var | awk 'NR==2 {print $4}')"
+        if [ $(df -m /var | awk 'NR==2 {print $4}') -lt ${REQUIRED_VAR_FREE} ]; then
+            printf "\r\033[3F\033[K$(date) [INFO]: Checking required resource.....................ng\n" | tee -a "${LOG_FILE}"
+            printf "\r\033[3E\033[K" | tee -a "${LOG_FILE}"
+            error "Lack of free space! Required at least ${REQUIRED_VAR_FREE} Bytes free space on /var directory."
+        fi
 
-    # Check free space of current directory 
-    info "'.' free space (MiB):         $(df -m . | awk 'NR==2 {print $4}')"
-    if [ $(df -m . | awk 'NR==2 {print $4}') -lt ${REQUIRED_DOT_FREE} ]; then
-        printf "\r\033[4F\033[K$(date) [INFO]: Checking required resource.....................ng\n" | tee -a "${LOG_FILE}"
-        printf "\r\033[4E\033[K" | tee -a "${LOG_FILE}"
-        error "Lack of free space! Required at least ${REQUIRED_DOT_FREE} Bytes free space on current directory."
+        # Check free space of current directory 
+        info "'${HOME}' free space (MiB):         $(df -m "${HOME}" | awk 'NR==2 {print $4}')"
+        if [ $(df -m "${HOME}"| awk 'NR==2 {print $4}') -lt ${REQUIRED_DOT_FREE} ]; then
+            printf "\r\033[4F\033[K$(date) [INFO]: Checking required resource.....................ng\n" | tee -a "${LOG_FILE}"
+            printf "\r\033[4E\033[K" | tee -a "${LOG_FILE}"
+            error "Lack of free space! Required at least ${REQUIRED_DOT_FREE} Bytes free space on current directory."
+        fi
+    else
+        # Check free space of /var
+        info "'${HOME}' free space (MiB):      $(df -m "${HOME}" || awk 'NR==2 {print $4}')"
+        if [ $(df -m /var | awk 'NR==2 {print $4}') -lt ${REQUIRED_VAR_FREE} ]; then
+            printf "\r\033[3F\033[K$(date) [INFO]: Checking required resource.....................ng\n" | tee -a "${LOG_FILE}"
+            printf "\r\033[3E\033[K" | tee -a "${LOG_FILE}"
+            error "Lack of free space! Required at least ${REQUIRED_VAR_FREE} Bytes free space on /var directory."
+        fi
     fi
     sleep 1
     printf "\r\033[4F\033[K$(date) [INFO]: Checking required resource.....................ok\n" | tee -a "${LOG_FILE}"
@@ -941,7 +951,7 @@ installation_cronjob() {
     # Backup current crontab
     crontab -l > $backup_file || :
 
-    if grep -q "Exastro auto generate" $backup_file; then
+    if ! grep -q "Exastro auto generate" $backup_file; then
         crontab -l 2>/dev/null > $output_file
         cat << _EOF_ >> $output_file
 ######## START Exastro auto generate (DO NOT REMOVE bellow lines.) ########
